### ISSUE TITLE
Wireframe what we want from this endeavor

### ISSUE THREAD

**Issue by lsunsi** [lsunsi/legendado#10]
The idea is simple, build up wireframes and plan ahead for what will be the pages we aim for the first bit of development. Something simple but representative of where we want to go.

**Comment by lsunsi** [comment]
![image](https://user-images.githubusercontent.com/6089867/65681028-8a9a5b80-e02e-11e9-94c6-3a94b0f57735.png)
![image](https://user-images.githubusercontent.com/6089867/65681038-90903c80-e02e-11e9-9965-00f9b65d4dc0.png)

**Comment by lsunsi** [comment]
We're going with these two basic views for now. Let's see if we can get to the point of working some more on the wireframes. We're trying not to get ahead of ourselves.

I think this issue is gonna be closed for now.

**Comment by FelipeRosa** [comment]
> We're going with these two basic views for now. Let's see if we can get to the point of working some more on the wireframes. We're trying not to get ahead of ourselves.
> 
> I think this issue is gonna be closed for now.

It was closed indeed.
